#+TITLE:   My Short Life As A Criminal
#+OPTIONS: num:nil toc:nil author:t
#+STYLE: <style>body {font-size: 12pt; line-height: 2em;}</style>

#* Synopsis

   There is nothing like the teen years to bring us face to face with
   the strange, the unexpected, the new.

#* Set the scene.

   It happened after my second semester at Northeastern University on
   my first co-op job, working for NASA at Cape Kennedy.  The job was
   a six month stint with a satellite monitoring team.

   It was a time when I was blazing many new trails: first child (of
   eight) to leave the nest, first to pursue a college degree, first
   white collar worker, and the first to fly.  That was the backdrop
   as both my parents and all my siblings gathered at Logan Field to
   send me off in the summer of 1967. 

   While the world about me was exploding with culture wars, Vietnam,
   free love, and drugs, I had managed to focus on wooing my childhood
   sweetheart, working to earn enough money to pay for college and
   avoiding the controversies swirling about me.

#* Working for NASA

   I had been working since the age of fourteen, but the job at NASA
   was a completely new experience for me.  For the previous five
   years, I had been cleaning tables, washing dishes and cooking
   pizzas.  But now I had a desk and wore a tie instead of an apron.
   I was scrubbing data from satellites, instead of scrubbing dishes, 
   and leaving work at 5:00 rather than arriving.  It was heady stuff
   and agreed with me.

   The team consisted of young engineers (who appeared ancient to me
   then but I recognize as having been mere lads in retrospect).  I
   thrived due to my strong work ethic.  There was no gopher task I
   wouldn't do and with a smile on my face.  My enthusiasm, youthful
   looks (more than one engineer commented that I looked more like a
   high school rather than a college freshman), and responsiveness to
   assigned tasks led to a puppy-like popularity and an invitation
   from Jim, the project lead engineer, to a party at his bachelor
   apartment on the beach.

#* Party Time (classic 60's rock)

   Jim's apartment, condo actually, was lush with assorted artwork,
   knickknacks, and music.  These were items I hadn't noticed missing
   from my co-op apartment.  It was my first exposure to Escher, Dali
   and Picasso.  Best of all was the stereo pumping out riveting
   sounds I was hearing for the first time, but certainly not for the
   last: _White Rabbit_, _Today_ and other *Surrealistic Pillow* gems
   from Jefferson Airplane, music from underground bands like the
   Kinks, The Doors, and Pink Floyd. And more San Francisco
   psychedelia like The Grateful Dead, Janis Joplin and Cheap Thrill.
   This was music I did not hear on AM radio back in Boston.  It was a
   life-changing experience.  I was intoxicated before even having my
   first drink or toke.

#* Wild night (underaged drinking)

   Hours later however the party was hopping and I was not alone in
   being stoned and drunk.  I was eighteen then and the legal drinking
   age in Florida was twenty-one.  When Ben, my manager, announced
   that his girl-friend was running around the complex naked, Jim was
   in a panic.  He knew that it was only a matter of time before the
   Condo Commandos would burst into action followed shortly by the
   arrival of the Cape Canaveral police.  Ben rounded up a group to
   search for the naked babe, and I volunteered, perhaps too eagerly,
   to leave no stone unturned in a (very grateful) effort to help.
   Jim told me to head out to the beach and walk south the two
   miles to my apartment complex, gently pointing out that it would
   not be a good idea for me to be present should the police show up.

#* Flight from Justice

   It was on the beach where the police found me, struggling mightily
   to figure out which way was south.  Sober, this was easy.  When
   the officer asked me if I had just come from the party, the answer
   was automatic, \ldquo{}What party?\rdquo.

   \ldquo{}Pahty.  OK, Boston.  So what are you doing on the beach at four
   o'clock in the morning\rdquo, the cop asked.  \ldquo{}And looking pretty tanked
   to me.\rdquo

   The adrenalin was helping to sober me up so I replied, with some
   truthfulness, \ldquo{}I like to run on the beach in the morning.  It's
   quiet and I can think clearly about problems.\rdquo

   \ldquo{}Well you are going to have some /real/ problems if I don't
   see a license or some ID pretty quick\rdquo, challenged the cop.

   It occurred to me that suggesting we drive to my apartment complex
   was a bad idea, not wanting to reveal my true age.  I truthfully
   replied, \ldquo{}I don't generally bring any identification while I'm out
   running.\rdquo

   \ldquo{}OK, wise guy, let's see your draft card\rdquo, was the next request.

   \ldquo{}Draft card?\rdquo, I said without thinking, not sure if I even had one.

   \ldquo{}Yes, draft cahd.  It is a federal law that anyone over
   eighteen must be registered for the draft.  Since you clearly have
   been drinking, you must be over twenty-one, now there's a good
   one\rdquo, he said the last parenthetically, under his breath,
   \ldquo{}so you're under arrest for not carrying your draft card on
   your person.  Please come with me\rdquo, and off to the police
   station we went.  I was finger printed, suffered ridicule from the
   cops (\ldquo{}Put this one in the nursery?\rdquo) and allowed to
   call Ben, who explained that he had some issues of his own but
   would come down as soon as he could.  The cops, clearly enjoying
   this crime solving business, were delighted to put me in a cell
   with a half dozen or so other /criminals/.

#* The smells and the characters

   I was now fully sober, very afraid and worried sick that my first
   co-op work experience was off to a dismal start and quick end.  But
   more than that, I was worried about the crowd observing me as the
   door shut behind me.  This was nothing like I had ever experienced.
   There were three or four foul smelling drunks lying on benches that
   lined the cell and one was asleep on a bench in the middle of the
   room.  The stench of booze, urine and body odor was gross and
   distasteful giving vent to the phrase, \ldquo{}assault to the
   senses\rdquo.  I'm certain that the look on my face revealed fully
   the disgust I felt.

   One man glared at me.  He was heavy set, balding, and was smoking
   an obnoxious cigar that did little to add to the ambiance.  As I
   look back on this scene, all I can see in my mind's eye is the
   image of Rush Limbaugh.  He glared while fending off a skinny,
   nervous looking blond guy who kept mumbling apologies and caressing
   him.  This was not a good sign.

#* The fight (Killer)

   It was the skinny nervous character who saw me as prey.  He turned,
   approached me and started making small talk.  He asked what I had
   done, if I needed a "friend", where I was from and so on.  When he
   started to invade my physical space, I got very nervous and started
   moving about.  I circled around the bench in the middle of the room
   with the sleeping drunk.  The blond was not aggressive or mean,
   just annoying and persistent.  After a couple of minutes of this
   silly dance, I announced, bravely for me, that I'd just as soon he
   leave me be.  It was a fight or flight moment, but there was no
   room to flee.  Luckily, the blond did not strike me as a fighter.
   But, when he was standing between me and the bench, I sort of
   instinctively shoved him towards the bench and let nature do the
   rest.  He toppled over and we all heard an audible and eery crack
   as his head met the concrete floor.

   More dread flooded over me as I saw blood seep out underneath his
   head.  All in the cell were now staring at me.  My heart racing and
   in a panic, I started calling for help and banging on the cell
   door.  A cop arrived almost immediately.  I protested that it was
   an accident and confessed to pushing the blond.  Rush Limbaugh
   nodded his agreement and simply added, \ldquo{}Yeah, the 'Killah'
   from Haavahd outsmarted Freddy\rdquo, using his best Boston accent.
   The cop tended to Freddy, radioed for an ambulance and told me to
   take it easy on the other guys.  By now Freddy was moaning but I
   nevertheless slunk into a corner chair certain that I'd be booked
   for manslaughter by lunch.  Ten minutes or so later the ambulance
   arrived and they carted Freddy off, moaning all the while.

#* Bailed out

   I never did find out what happened to Freddy.  Shortly after he was
   wheeled out, Ben arrived.  Smiling, he said to the cop, \ldquo{}Yes
   sir, he works for me and we do have to keep him on a short leash, a
   real menace, this one.  I'll see to it that he stays out of trouble
   for a few weeks anyway\rdquo.  They both laughed but I did not
   see the humor.

   After bailing me out and paying the fifty dollar fine, Ben filled
   me in on the end of the party.  His girl friend was found skinny
   dipping in the pool, fortunately in the shallow end but was now
   sleeping it off in Jim's condo.  He also told me that he had
   overheard \ldquo{}some kid named Killah from Boston had beat the
   crap out of Freddy the Queer\rdquo.  I slid down in my seat, nearly
   all the way to the floor.  And lastly, he told me that he saw no
   reason why this incident should get any mention at work, more music
   to my ears.

#* Back to work

   The NASA co-op folks evidently never did get wind of the incident,
   at least not in any official sense.  I frequently noticed a telling
   smile on faces I hardly recognized as I executed my gopher tasks
   around the Satellite Tracking complex.  I eventually finished the
   six month tour.  When it was done I never again endured the moniker
   "Killah".  Even better, my family did not get wind of this incident
   until years later, lest the prodigal son image be tarnished in any
   way.


