#+TITLE: The Royal Triscuit Lesson
#+OPTIONS: num:nil toc:nil author:t creator:nil
#+STYLE: <style>body {font-size: 12pt; line-height: 2em;}</style>

  It was approaching midnight as I pulled into the football field
  parking lot.  I had agreed to participate as a Relay For Life
  chaperone in an all night fund raiser at my step-daughter's high
  school.  The parking lot was packed, which was my first surprise.

  As I moved from the parking lot to the track, it was misting and,
  except for the candles and low-level lighting dotting the field,
  quite dark.  Tents and small tables with portable folding chairs
  also covered the field.  The teens who were not circling the track
  were in these tents and at the tables playing games, talking,
  laughing and generally having a good time.  But certainly not all of
  them.

  Heather, my step-daughter, was a junior and starting to date.  An
  attractive, tall, long legged, blond, she was late to the dating
  game, which surprised me and relieved her mother.  Given her looks,
  quick wit and "party time" demeanor, I was amazed that a steady
  drum beat of young men were not yet vying for her attentions.

  Karl, a nice kid, but so wrong for Heather, was the first.  The best
  we hoped for was that she would begin to learn about how she wanted
  to relate to the opposite sex.  As I circled the field, I saw just
  how bad it was going.  Karl doing his part, was walking around the
  track towards me with a young babe under each arm, neither of which
  was Heather.  My blood started to boil.  Karl saw me and the
  unrestrained glare on my face.  It said all that was necessary.  He
  immediately turned his gaze to the ground and kept walking past.

  \ldquo{}I don't suppose you've seen Heather?\rdquo I asked, making
  it clear that I was not about to pretend I didn't see what was
  impossible to miss.  He stopped, and turned back to me, shedding his
  babes for the moment.

  \ldquo{}I think she's in the girl's room with Liz and Rachel.\rdquo
  was all he needed to say for me to know that she was surely
  distraught.  He turned, reattached his friends and they were
  off.

  As I approached the bathrooms at the edge of the field, I saw Liz
  and Rachel turn the corner doing damage control with Heather between
  them.  I decided then to re-tell Heather the story of Royal
  Triscuit, with more depth in this telling.  The story had taken
  place about five years earlier, when she was twelve, or so.


  Royal Triscuit, imagined by me to be a distant relative to
  Seabiscuit, was a spectacularly beautiful, black Arabian stallion.
  When I saw him for the first time, knowing that I would soon be
  riding him through the mountains and along the coast in Northern
  California, I could only think, \ldquo{}My God, what have I got
  mself into?\rdquo  Sandy, Heather's mom, my wife of five years was
  admiring the Arabian she'd be riding.  She was clearly filled with
  anticipation and looking forward to what was about to unfold.

  But first things first.  I need to back up a few months.  Heather's
  Royal Triscuit Lesson began as Sandy and I were approaching our
  fifth wedding anniversary.  I looked forward to each anniversary as
  an opportunity to present Sandy with a special gift or experience to
  celebrate our marriage.  The first few years it was jewelry.  Then a
  long weekend stay at some National Landmark Hotels (The Biltmore in
  Providence, The Northampton Inn in Northampton, MA).  But with our
  fifth, I was looking for something different.  And of course, I had
  not a clue what that might be.

  It was around that time that Sandy and Heather were wrapping up a
  few years of horseback riding lessons.  Heather's interest after a
  few years was on the wane.  It wasn't that she was losing interest
  in riding as much as her focus was expanding to include theater,
  music, friends, art, poetry, etc.  Knowing that Sandy loved riding,
  I agreed to take Heather's place and keep her company even though my
  recent riding experience consisted mainly of falling off the horse
  while trying to dismount.  I did manage to get better but the fear
  meter went off the charts any time a horse decided to advance past a
  walk.

  During one of these rides, the notion occurred to me to plan a
  horseback riding vacation to celebrate our next wedding anniversary.
  After much googling, I settled on Ricochet Ridge Ranch in Northern
  California.  They had a perfect Romantic Ride weekend package.  So I
  set it up.

  When the agent asked, \ldquo{}And how much experience do you each
  have?\rdquo I immediately sensed a trap.  Do I admit to being a
  duffer and risk being assigned circus ponies instead of real horses?
  Do I risk a less than memorable experience for Sandy?

  My answer was instant, \ldquo{}Oh, we've been riding for years and
  years,\rdquo which was sort of true, if you added my month and her
  years.

  \ldquo{}Excellent!\rdquo{} the agent exclaimed.  \ldquo{}We'll put
  you on the Arabians.\rdquo I felt a sense of relief at having
  out-smarted the agent and insuring that Sandy would be delighted
  with our mounts.  Quickly followed by a sense of dread at having
  out-smarted myself with a risk of serious bodily damage.  But then I
  thought, \ldquo{}How bad could it be?\rdquo

  The time arrived and we flew out to San Francisco, then drove up to
  Medocino, across the Golden Gate bridge, with a serene stop at Muir
  Woods and a lingering, panoramic drive through wine country.  The
  trip was a success even before we got close to the ranch.

  Arriving at the ranch first thing on Saturday morning, we watched a
  safety video while Carolyn, our trail guide, packed the horses into
  the trailer.  We then hopped into the truck and drove off to some
  woods about ten miles away where we saddled up and began the ride.

  All three horses were Arabians, who are famous for speed and
  endurance (I kept thinking of the movie _Hidalgo_).  Carolyn, in the
  lead, rode Victory, a beautiful brown mare.  Sandy followed on Indy,
  a brilliant white stallion, very reminiscent of Tolkien's Shadowfax.
  I brought up the rear with Royal Triscuit, a majestic black beast,
  who was literally chomping at the bit to let loose some of that
  latent Arabian energy.

  When we hit the first rise in the trail, Triscuit did indeed let
  loose!  We were forewarned by Carolyn that the Arabians like to
  canter and gallop up the hills so when Triscuit took off, it was not
  a shock, but it was a \ldquo{}are you a man or a wuss\rdquo
  moment.  I grabbed onto the reins with one hand, the saddle horn
  with the other.  Triscuit went flying past Sandy, then past Carolyn
  and attacked the hill.  For the next fifteen minutes or so the horse
  gave it all he was worth.  I held on for dear life, amazed with each
  passing second that I was not lying on the ground.  It was an
  adrenalin rush for me.  For the first time in my short riding life,
  I felt relaxed and comfortable while riding at a gallop.

  I felt bad for Sandy because she could not know that I was enjoying
  the ride immensely.  If I could have managed it, I would have turned
  around to let her see the smile on my face, but trick riding was not
  yet in my repertoire.  When she finally caught up to me, she was
  greatly relieved to see the huge grin on my face.

  After a couple of hours riding through the redwood forests we took a
  break for lunch in a fenced in area at the top of a hill overlooking
  the Pacific Ocean.  The view was simply spectacular.  While we ate
  and enjoyed the gorgeous scene, the horses ran together around the
  field and rolled in the grass.

  After lunch, we headed back down the mountain.  The horses, to my
  relief, were disinclined to race down the hill.  My rear end was
  sore.  Four hours in the saddle was three more than I'd ever done at
  one time.  As we approached the trailer I was feeling giddy.  I had
  enjoyed it immensely, survived with no (visible) damage and still
  had energy.  Imagine my surprise when Carolyn tells us, as she is
  packing the horses into the trailer, that we will now head over to
  another hill a mile or so away!

  Sandy was having a ball, enjoying this immensely.  How could I
  possibly say, \ldquo{}That's OK, take the rest of the afternoon off,
  I have plans for a much deserved nap right about now ...?\rdquo It
  was time to buck up and tough out the next phase.  We started out
  easy, leading me to believe that the breakneck pace was behind us.
  However, we hit the first rise on the new trail and all three horses
  burst into hill climbing mode.  Every bone and muscle in my body was
  starting to ache.  Fortunately, Triscuit had burned out and could
  not catch Indy or Victory, making for a much less scary ride.

  After six hours in the saddle, Carolyn got us back to the trailer
  and we took a leisurely drive back to the ranch.  I was feeling
  smug.  I had survived, had more fun than I expected and Sandy was
  basking in her love of riding.

  As I finished telling Heather the Royal Triscuit story, she looked at me
  quizically and asked, \ldquo{}What has this got to do with
  anything?\rdquo

  \ldquo{}Heather,\rdquo I replied, \ldquo{}search for boys, and men,
  who will treat you like the Goddess you are, like the Goddess your
  mother is.  If a boy is not willing or able to treat you like I
  treat your mother, then lose him faster than it takes Royal Triscuit
  to fly up a mountain.\rdquo

  She said nothing but shot me a look that said, \ldquo{}How can you
  be so stupid?\rdquo{}.  Resigned, I knew I'd be giving the Royal
  Triscuit Lesson again, altogether too soon.
  
